[package]
name = "rust-gl"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = ["dynamic_linking"] }

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
